name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build Prebid.js
        run: gulp build --modules=appnexusBidAdapter,rubiconBidAdapter,googleAnalyticsAdapter

      - name: Deploy to Server
        run: scp dist/prebid.js user@server:/path/to/deploy
